spring:

  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: spring
    password: spring
    driver-class-name: org.postgresql.Driver

  # Hibernate ddl auto (create, create-drop, validate, update)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025

  solr:
    host: http://localhost:8983/solr/demo

application:
  security:
    jwt:
      secret-key: 24fa3955dc6677b0827f1d6cb2b87b898967588e26c61d7d42485b85afb06385866d3fb95635fc3b6270cc96aa02cee56553a784fd9afb818e66ea59eeefd07da
      expiration: 8640000
  mailing:
    default-email: test@test.be
    frontend:
      activation-url: http://localhost:4200/activate #http://127.0.0.1:8080/api/v1/auth/activate-account
      password-url: http://localhost:4200/new-password
  file:
    uploads:
      photos-output-path: ./uploads
  cors:
    origins: http://localhost:4200, http://127.0.0.1:4200, http://127.0.0.1
logging:
  level:
    org:
      springframework: DEBUG
      springframework.orm.jpa: DEBUG
      springframework.transaction: DEBUG
      springframework.transaction.interceptor: DEBUG
      springframework.security.web.FilterChainProxy: DEBUG
      springframework.jdbc: DEBUG