spring:

  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:postgresql://postgres:5432/demo
    username: spring
    password: spring
    driver-class-name: org.postgresql.Driver

  # Hibernate ddl auto (create, create-drop, validate, update)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: mail-dev
    port: 1025

  cors:
    origins: http://localhost:4200, http://127.0.0.1:4200, http://127.0.0.1

application:
  security:
    jwt:
      secret-key: 24fa3955dc6677b0827f1d6cb2b87b898967588e26c61d7d42485b85afb06385866d3fb95635fc3b6270cc96aa02cee56553a784fd9afb818e66ea59eeefd07da
      expiration: 8640000
  mailing:
    default-email: test@test.be
    frontend:
      activation-url: http://127.0.0.1/activate #http://127.0.0.1:8080/api/v1/auth/activate-account
  file:
    uploads:
      photos-output-path: ./uploads

logging:
  level:
    org:
      springframework.orm.jpa: DEBUG
      springframework.transaction: DEBUG
      springframework.transaction.interceptor: DEBUG
      springframework.security.web.FilterChainProxy: DEBUG
      springframework.jdbc: DEBUG