spring:
  server:
    port: 8088

  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: spring
    password: spring
    driver-class-name: org.postgresql.Driver

  # Hibernate ddl auto (create, create-drop, validate, update)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025

logging:
  level:
    org:
      springframework: DEBUG
      springframework.orm.jpa: DEBUG
      springframework.transaction: DEBUG
      springframework.transaction.interceptor: DEBUG
      springframework.security.web.FilterChainProxy: DEBUG
      springframework.jdbc: DEBUG