spring:

  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  thymeleaf:
    mode: HTML5

server:
  port: 8088
  servlet:
    context-path: /api/v1/
